version: '3.8'

services:
  h2-database:
    image: oscarfonts/h2
    container_name: h2_database
    ports:
      - "81:81"  
      - "1521:1521"  
    environment:
      - H2_OPTIONS=-ifNotExists -baseDir /opt/h2-data
    volumes:
      - h2_data:/opt/h2-data  
    restart: unless-stopped

volumes:
  h2_data:
    driver: local
