version: '3.8'

services:
  h2-database:
    image: oscarfonts/h2
    container_name: h2_database
    ports:
      - "8082:8082"  # H2 Web-Konsole
      - "1521:1521"  # Port für Java-Verbindung
    volumes:
      - h2_data:/opt/h2-data # Persistente Datenbank 

volumes:
  h2_data:
    driver: local
